<?php

/**
 * @file
 * Add Siteimprove functionality and js.
 */

/**
 * Implements hook_menu().
 */
function itk_siteimprove_menu() {
  $items = array();

  $path = drupal_get_path('module', 'itk_siteimprove');

  $items['admin/config/system/itk-siteimprove'] = array(
    'title' => 'ITK Siteimprove',
    'description' => 'Manage ITK Siteimprove settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('itk_siteimprove_form'),
    'access arguments' => array('administer itk siteimprove'),
    'file' => 'itk_siteimprove.admin.inc',
    'file path' => $path . '/includes',
  );

  return $items;
}

/**
 * Add new permission.
 *
 * @return array
 *   An array defining a permission.
 */
function itk_siteimprove_permission() {
  return array(
    'administer itk siteimprove' => array(
      'title' => t('Administer ITK Siteimprove module'),
      'description' => t('Perform administration tasks related to ITK Siteimprove.'),
    ),
  );
}

/**
 * Implements hook_preprocess_page().
 *
 * Add script if all conditions pass.
 */
function itk_siteimprove_page_alter(&$page) {
  $key = variable_get('itk_siteimprove_key');

  // Ignore if key is not set.
  if (!$key) {
    return;
  }

  // Check for excludes.
  $excludes = variable_get('itk_siteimprove_exclude_patterns');
  $excludePatterns = $excludes ? $excludes : [];

  $trackPath = TRUE;
  $currentPath = '/' . current_path();

  // Check each exclude pattern.
  foreach ($excludePatterns as $pattern) {
    if (preg_match($pattern, $currentPath)) {
      $trackPath = FALSE;
      break;
    }
  }

  // Inject script if allowed path.
  if ($trackPath) {
    drupal_add_js(drupal_get_path('module', 'itk_siteimprove') . '/js/itk-siteimprove.js', [
      'type' => 'file',
      'scope' => 'footer',
    ]);
    drupal_add_js(array(
      'itk_siteimprove' => array(
        'key' => $key,
      ),
    ), 'setting');
  }
}
